#!/usr/bin/perl
use strict;
use utf8;
use warnings;
use CPAN::Flatten;

my $package = shift or die "Usage: flatten Package::Name\n";
my $flatten = CPAN::Flatten->new;
my $distributions = $flatten->flatten($package);
print "\n", $distributions->emit;

__END__

=head1 SYNOPSIS

  > flatten Package::Name

=head1 DESCRIPTION

TBD

=head1 AUTHOR

Shoichi Kaji

=cut

