#!/usr/bin/perl
use strict;
use utf8;
use warnings;
use CPAN::Flatten;

my $package = shift or die "Usage: flatten Pacakge::Name\n";

my $flatten = CPAN::Flatten->new;

my $artifacts = $flatten->flatten($package);

print "\n--> Detect the following dependencies:\n";
for my $artifact (grep !$_->is_core, @$artifacts) {
    print " ", $artifact->name, "\n";
}

__END__

=head1 SYNOPSIS

  > flatten Package::Name

=head1 DESCRIPTION

TBD

=head1 AUTHOR

Shoichi Kaji

=cut

